### ISSUE TITLE
Unable to install shiphawk-ruby via rubygems; either update readme or host on rubygems again

### ISSUE THREAD

**Issue by quetzaluz** [ShipHawk/shiphawk-ruby#7]
Greetings,

Two weeks ago I was able to install the shiphawk-ruby gem following the instructions in this repository's README.md file. However, this no longer appears to work. Another developer and myself have tried repeatedly to install with and without `:git` and `:github` source specified and we get the following message or variations thereof:

`Could not find gem 'shiphawk-ruby (>= 0) ruby' in git://github.com/ShipHawk/shiphawk-ruby.git (at master).`

We also took other steps to troubleshoot such as changing our rubygems source destination to be both http and https.

Searching rubygems.org shows no entries for shiphawk.

Please advise if shiphawk-ruby will be installable following the instructions in this readme, or if this functionality is being deprecated.

**Comment by aaronshiphawk** [comment]
Hi, the README file was out of date and referenced the name of the gem as shiphawk-ruby when it is just shiphawk. I pushed the latest up to RubyGems so you should be able to just do gem 'shiphawk', '0.8.1'.

**Comment by salazareddie** [comment]
Hi Aaron,

Thanks for the help! Looks like we are up and running.

Eddie

**Comment by quetzaluz** [comment]
Thanks, closing this now.
